options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.120; };
    listen-on-v6 { none; };

    recursion yes;

    allow-recursion {
        172.30.0.0/24;
    };

    allow-query {
        172.30.0.0/24;
    };

    dnssec-validation yes;
};

trust-anchors {
    "." static-ds 33493 13 2 "D52E4AB2F35B2931983579C3056F994F71D0E52FA26E091853DEF075181B111D";
};

zone "." {
    type hint;
    file "/var/lib/bind/db.root.hints";
};

