options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.20; };
    listen-on-v6 { none; };

    recursion no;

    allow-query { any; };
};

zone "unsigned" {
    type primary;
    file "/var/lib/bind/db.unsigned";
};
