options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.100; };
    listen-on-v6 { none; };

    recursion yes;

    allow-recursion {
        172.30.0.0/24;
    };

    allow-query {
        172.30.0.0/24;
    };

    dnssec-validation no;
};

zone "." {
    type hint;
    file "/var/lib/bind/db.root.hints";
};
