options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.60; };
    listen-on-v6 { none; };

    recursion no;

    allow-query { any; };
};

zone "gamma.signed" {
    type primary;
    file "/var/lib/bind/db.gamma.signed";
};

