options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.10; };
    listen-on-v6 { none; };

    recursion no;

    allow-query { any; };
};

zone "." {
    type primary;
    file "/var/lib/bind/db.root.signed";
};


